#!/bin/bash
set -e
export DOTFILES=~/.dotfiles

git submodule update --init --recursive

stow zsh
stow vim
stow nvim
stow i3
stow bin
stow tmux
stow yaourt
stow libinput-gestures
stow git
stow bash
# sudo stow -t / xorg

echo "Install vim-plug"
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo "Install vim/nvim plugins"
vim +PlugInstall +qall
nvim +PlugInstall +qall
