#!/bin/bash
export PATH="~/bin:$PATH"
export DOTFILES=~/.dotfiles

git submodule update --init --recursive
stow vim tmux zsh xresources yaourt nvim i3 libinput-gestures

echo "Install vim-plug"
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo "Install vim/nvim plugins"
vim +PlugInstall +qall
nvim +PlugInstall +qall
