#!/bin/bash

if ! ping -c 1 176.34.135.167 &> /dev/null; then
    echo ""
    exit
fi

API="http://api.fixer.io/latest"
text=$(curl ${API} 2> /dev/null | jq -r '.rates.GBP')
icon=""

if [[ $BLOCK_INSTANCE ]]; then
  read -a array <<< $BLOCK_INSTANCE
  text=$(curl ${API}?base=${array[0]} 2> /dev/null | jq -r ".rates.${array[1]}")

  case ${array[1]} in
    ("EUR") icon="";;
    ("GBP") icon="";;
    ("USD") icon="";;
  esac
fi

echo "<span foreground=\"#999\">${icon}</span>  ${text}"
