#!/bin/python

import threading
import sys
import time
import paho.mqtt.client as mqtt

lamps = [{'id': 'name', 'status': 0}, {'id': 'name', 'status': 0}]
main_topic = "topic"
status_topic = "status/#"
colour_hex = "#999"
icon = ""


def on_connect(client, userdata, flags, rc):
    client.publish(main_topic, "status")
    client.publish(main_topic, "colour?")
    client.subscribe(main_topic)
    client.subscribe(status_topic)


def on_message(client, userdata, msg):
    message = str(msg.payload, 'utf-8')
    colour_hex = '#999'

    for lamp in lamps:
        if lamp['id'] in msg.topic:
            lamp['status'] = int(message)

    if msg.topic == main_topic and message.startswith("RGB"):
        r = int(message[4:].split(',')[0])
        g = int(message[4:].split(',')[1])
        b = int(message[4:].split(',')[2])
        colour_hex = '#%02x%02x%02x' % (r, g, b)
        print('<span foreground="%s">%s</span>' % (colour_hex, icon))

    online = False
    for lamp in lamps:
        if lamp['status'] == 1:
            online = True

    if not online:
        print('<span foreground="%s">%s</span>' % (colour_hex, icon))

    sys.stdout.flush()


if __name__ == "__main__":
    client = mqtt.Client()
    client.on_connect = on_connect
    client.on_message = on_message

    client.connect("server", 1883, 60)
    print("<span foreground=\"%s\">%s</span>" % (colour_hex, icon))
    client.loop_forever()   # blocking function
