#!/bin/bash

if ! ping -c 1 176.34.135.167 &> /dev/null; then
    echo ""
    exit
fi

if [[ "$BLOCK_BUTTON" == 1 ]]; then
  i3-msg "exec urxvt -name yaourt -e zsh -c \"yaourt -Suya\"" > /dev/null
fi

pac=$(checkupdates | wc -l)
aur=$(yaourt -Qqu -a| wc -l)

check=$((pac + aur))
if [[ "$check" != "0" ]]
then
    echo "$pac  $aur"
fi
