#!/bin/bash

if ! ping -c 1 192.168.1.78 &> /dev/null; then
    echo ""
    exit
fi

if [[ "${BLOCK_BUTTON}" == "1" ]]; then
  xdg-open http://192.168.1.78:8384 > /dev/null
fi

echo "<span foreground=\"#999\"></span>"
exit
