#!/bin/bash

SYNCTHING=$(pgrep syncthing)

if [[ "${BLOCK_BUTTON}" == "1" ]]; then
  xdg-open http://localhost:8384
fi

if [[ "${SYNCTHING}" != "" ]]; then
  echo "<span foreground=\"#999\"></span>"
  echo "<span foreground=\"#999\"></span>"
  echo ""
fi
