#!/bin/bash
# Based on http://openweathermap.org/current

ping -q -w 2 -c 1 176.34.135.167 > /dev/null
online=$?
if [ ! $online -eq 0 ]; then
    echo ""
    echo ""
    echo ""
    exit
fi

API_KEY="5b2f2f1f58cf145223342ccc5530c884"

# Check on http://openweathermap.org/find
CITY_ID="${BLOCK_INSTANCE}"

URGENT_LOWER=0
URGENT_HIGHER=30

ICON_SUNNY=""
ICON_CLOUDY=""
ICON_RAINY=""
ICON_STORM=""
ICON_SNOW=""
ICON_FOG=""

SYMBOL_CELSIUS="℃"

WEATHER_URL="http://api.openweathermap.org/data/2.5/weather?id=${CITY_ID}&appid=${API_KEY}&units=metric"

WEATHER_INFO=$(wget -qO- "${WEATHER_URL}")
WEATHER_MAIN=$(echo "${WEATHER_INFO}" | grep -o -e '\"main\":\"[a-Z]*\"' | awk -F ':' '{print $2}' | tr -d '"')
WEATHER_TEMP=$(echo "${WEATHER_INFO}" | grep -o -e '\"temp\":\-\?[0-9]*' | awk -F ':' '{print $2}' | tr -d '"')

if [[ "${WEATHER_MAIN}" = *Snow* ]]; then
  icon=${ICON_SNOW}
elif [[ "${WEATHER_MAIN}" = *Rain* ]] || [[ "${WEATHER_MAIN}" = *Drizzle* ]]; then
  icon=${ICON_RAINY}
elif [[ "${WEATHER_MAIN}" = *Cloud* ]]; then
  icon=${ICON_CLOUDY}
elif [[ "${WEATHER_MAIN}" = *Clear* ]]; then
  icon=${ICON_SUNNY}
elif [[ "${WEATHER_MAIN}" = *Fog* ]] || [[ "${WEATHER_MAIN}" = *Mist* ]]; then
  icon=${ICON_FOG}
else
  icon=""
  # echo "${WEATHER_MAIN} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
  # echo "${WEATHER_MAIN} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
  # echo ""
fi

echo "<span foreground=\"#999\">${icon}</span>  ${WEATHER_MAIN}, ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
echo "<span foreground=\"#999\">${icon}</span>  ${WEATHER_MAIN}, ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
echo ""

if [[ "${WEATHER_TEMP}" -lt "${URGENT_LOWER}" ]] || [[ "${WEATHER_TEMP}" -gt "${URGENT_HIGHER}" ]]; then
  exit 33
fi
