# Path to your oh-my-zsh installation.  export ZSH=/home/alex/.oh-my-zsh
export TERM="xterm-256color"
export DOTFILES=$HOME/.dotfiles
export ZSH=$DOTFILES/zsh/oh-my-zsh
export BASE16=mocha
ZSH_CUSTOM=$DOTFILES/zsh/custom
ZSH_THEME="promptline"

# Base16 Shell
BASE16_SHELL="$DOTFILES/base16-shell/base16-$BASE16.dark.sh"
[[ -s $BASE16_SHELL  ]] && source $BASE16_SHELL

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

plugins=(git extract sudo virtualenv zsh-syntax-highlighting)

# User configuration

  export PATH="/home/alex/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

alias :q="exit"
alias dot="cd $DOTFILES"

alias vims="vim -S"
alias tmux="tmux -2"
alias zshrc="vim $DOTFILES/zsh/zshrc"
alias vimrc="vim $DOTFILES/vimrc"
alias tmuxrc="vim $DOTFILES/tmux/tmux.conf"
alias venvrc="vim $VIRTUAL_ENV/bin/postactivate"

alias sv="source $DOTFILES/zsh/zshrc"
alias bootwindows="sudo grub-reboot 'Windows Boot Manager (on /dev/sdb2)' && sudo reboot"

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

### VirtualEnvWrapper
export WORKON_HOME=$HOME/.virtualenvs
source /usr/local/bin/virtualenvwrapper.sh
